services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: lvlup-rails-api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/lvlup_cms_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    volumes:
      - ./api:/rails
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4000:4000"
    command: bundle exec rails server -b 0.0.0.0 -p 4000

  db:
    image: postgres:16-alpine
    container_name: lvlup-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lvlup_cms_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: lvlup-redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
